apiVersion: v1
kind: Service
metadata:
  name: api-clinicorp-service
  namespace: devops-challenge
spec:
  type: NodePort
  selector:
    app: api-clinicorp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30007